version: '2'
# 定义ftp服务
services:
  ftpd:
    #privileged: true
    image: wisbyme/lnmpsite-ftpd:latest
    volumes:
      - ../nginx/www:/home/ftpusers/coder
      - ./pure-ftpd:/etc/pure-ftpd
    
    ports:
      - "20-21:20-21"
      - "30000-30032:30000-30032"
    
    environment:
      PUBLICHOST: localhost
      FTP_USER: coder
      FTP_PASSWORD: 1234567890
      
    restart: unless-stopped
    container_name: ftpd
