version: '2'
# 定义服务nginx,php,mysql,redis,ftp,backup
services:
  ftpd:
    depends_on:
      - nginx
    
    image: wisbyme/lnmpsite-ftpd:hardened
    #build: ./ftpd
    
    volumes:
      - ./nginx/www:/home/ftpusers/coder
      - ./ftpd/pure-ftpd:/etc/pure-ftpd
    
    ports:
      - "20-21:20-21"
      - "30000-30032:30000-30032"
    networks:
      - frontend
    
    environment:
      PUBLICHOST: localhost
      FTP_USER: $FtpUser
      FTP_PASSWORD: $FtpUserPasswd
      
    restart: unless-stopped
    container_name: ftpd
    
  nginx:
    # 依赖php服务，意味着在启动nginx之前先启动php
    depends_on:
      - php
    
    # nginx镜像的路径
    image: wisbyme/lnmpsite-nginx:1.14.1
    #build: ./nginx
    
    # 使nginx容器把网站文件和目录存放到主机目录中，持久化和方便管理
    volumes:
      - ./nginx/ssl/nginx.crt:/etc/nginx/cert/nginx.crt
      - ./nginx/ssl/nginx.key:/etc/nginx/cert/nginx.key
      - ./nginx/ssl/cloudflare.crt:/etc/nginx/cert/cloudflare.crt
      - ./nginx/www:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./log/nginx.log:/var/log/nginx/error.log

    # nginx意外退出时自动重启
    restart: always

    # 映射808和443端口
    ports:
      - "808:808"
      - "443:443"
    networks:
      - frontend

    # 容器名称
    container_name: nginx

  php:
    depends_on:
      - mysql
      - redis
    
    image: wisbyme/lnmpsite-php:7.2.12
    #build: ./php
    
    ports:
      - "9901"
    networks:
      - frontend
      - backend     
      
    volumes:
      - ./php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
      - ./php/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
      - ./php/php.ini:/usr/local/php/etc/php.ini
      - ./log/php-fpm.log:/usr/local/php/var/log/php-fpm.log
      - ./nginx/www:/usr/share/nginx/html
      
    restart: always
    container_name: php

  # MySQL
  mysql:
    image: wisbyme/lnmpsite-mysql:5.7.18
    #build: ./mysql
    ports:
      - "127.0.0.1:3306:3306"
      
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
      
    environment:
      MYSQL_ROOT_PASSWORD: $MySQLpwd
      
    command: ['mysqld', '--character-set-server=utf8']
    networks:
      - backend
    restart: always
    container_name: mysql

  # REDIS
  redis:
    image: wisbyme/lnmpsite-redis:4.0.11
    #build: ./redis
    
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - backend
    
    volumes:
      - ./redis/redis.conf:/usr/local/redis/redis.conf
      - ./log/redis.log:/usr/local/redis/redis.log
    restart: always
    container_name: redis

networks:
  frontend:
  backend:
