version: '2'

# 定义backup服务
services:
  backup:
    privileged: true
    image: wisbyme/lnmpsite-backup:latest
    volumes:
      - ./site:/tmp/backup
      - ./task:/tmp/crontask
    
    environment:
      #Using ge.tt
      GETT_TOKEN: 
      GETT_SHARE_NAME: 
      
      #Using Tencent Cloud
      secret_id: AKID15IsskiBQACGbAo6WhgcQbVls7HmuG00
      secret_key: csivKvxxrMvSvQpMWHuIz12pThQQlWRW
      region: ap-beijing-1
      bucketname: test04-123456789
      
    restart: unless-stopped
    container_name: backup
    
