version: '2'

# 定义backup服务
services:
  backup:
    privileged: true
    image: wisbyme/lnmpsite-backup:latest
    volumes:
      - /home/lnmpsite:/home/site
      - /home/lnmpback:/home/backup
      - ./keepactive.sh:/usr/bin/keepactive.sh
    
    environment:
      #Using TeraCloud
      tcuserid: $Tcuserid
      tcpasswd: $Tcpasswd
      tcdevaddr: $Tcdevaddr
      
      #Using Ge.tt (保留)
      apikey: $ApiKey
      email: $UserEmail
      password: $UserPasswd
      
      #Using Tencent Cloud
      secret_id: $SecretID
      secret_key: $SecretKey
      region: $Region
      bucketname: $BucketName
      
    restart: unless-stopped
    container_name: backup
    
